From: "Trevor Joynson (trevorj)" <github@skywww.net>
Date: Wed, 14 Dec 2016 13:29:17 -0800
Subject: Python 3.2 on precise does not have PyASCIIObject in scope

---
 src/frob.cc | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/frob.cc b/src/frob.cc
index 478c44d..143ac58 100644
--- a/src/frob.cc
+++ b/src/frob.cc
@@ -27,6 +27,10 @@
 #include <Python.h>
 #include <frameobject.h>
 
+#if PYFLAME_PY_VERSION == 3
+#include <unicodeobject.h>
+#endif
+
 #include "./config.h"
 #include "./exc.h"
 #include "./ptrace.h"
